FROM python:3.10-slim

WORKDIR /app

COPY pyproject.toml .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir pandas numpy scikit-learn redis mlflow cloudpickle

COPY src/ src/
COPY consumer.py .

ENV PYTHONUNBUFFERED=1
ENV REDIS_HOST=redis
ENV REDIS_PORT=6379

CMD ["python", "consumer.py"]
